project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://leonardys.github.io
  title: "Leonard Yulianus"
  navbar:
    right:
      - blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/leonardys
      - icon: rss
        href: index.xml
  google-analytics:
    tracking-id: "G-YJ31ZEQ0PZ"
    anonymize-ip: true

format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
